#### KAMAMO LESLEY WANJIKU
#### 8984971
#### CSCN8020-26W-Sec1- Reinforcement Learning Programming


### PROBLEM 1

`Pick-and-Place Robot`:

Consider using reinforcement learning to control the motion of a robot arm
in a repetitive pick-and-place task. If we want to learn movements that are fast and smooth, the
learning agent will have to control the motors directly and obtain feedback about the current positions
and velocities of the mechanical linkages.
Design the reinforcement learning problem as an MDP, define states, actions, rewards with reasoning.

The pick-and-place robot arm is modeled as an MDP where the state includes joint angles and task context (contact state), ensuring the Markov property.
We model the task as an MDP:
(S,A,P,R,γ)

At each discrete control step t(e.g., every 20–50 ms), the agent observes state s_t, chooses action a_t, the robot transitions to s_(t+1), and receives reward r_(t+1)
The actions are continuous motor commands (joint torques, plus gripper open/close), matching low-level control for smooth motion. Transitions follow robot dynamics with possible stochasticity from noise and friction. The reward combines a large success reward for placing the object, a per-step time penalty to encourage speed, and smoothness/energy penalties on torque magnitude and torque changes to reduce jerk and wear, optionally shaped by distances to the object/goal to improve learning. A high discount factor (e.g., γ=0.99) values completing the full task sequence.


### PROBLEM 2


`Tasks`

Perform two iterations of Value Iteration for this gridworld environment. Show the step-by-step process
(without code) including policy evaluation and policy improvement. Provide the following for each
iteration:

`• Iteration 1:`

1. Show the initial value function (V) for each state.

2. Perform value function updates.

3. Show the updated value function.

1. Initial Value Function

[
V_0(s_1)=0,\quad
V_0(s_2)=0,\quad
V_0(s_3)=0,\quad
V_0(s_4)=0
]


2. Policy Evaluation Step (Using Initial Policy π₀)

Since
[
\pi_0(\text{up}|s)=1
]
we evaluate:

[
V_1(s)=R(s)+\gamma V_0(s')
]

where (s') is the next state when taking action **up**.

Because (V_0(s)=0) for all states:

* For (s_1): up hits wall → stays in (s_1)
  [
  V_1(s_1)=5+0.9(0)=5
  ]

* For (s_2): up hits wall → stays in (s_2)
  [
  V_1(s_2)=10+0.9(0)=10
  ]

* For (s_3): up → (s_1)
  [
  V_1(s_3)=1+0.9(0)=1
  ]

* For (s_4): up → (s_2)
  [
  V_1(s_4)=2+0.9(0)=2
  ]

_Updated Value Function after Iteration 1:_

[
V_1=
\begin{cases}
s_1=5 \
s_2=10 \
s_3=1 \
s_4=2
\end{cases}
]



3. Policy Improvement Step

Now we improve the policy by choosing the action that maximizes:

[
Q(s,a)=R(s)+\gamma V_1(s')
]


**State (s_1)**

* up: (5+0.9(5)=9.5)
* left: (5+0.9(5)=9.5)
* right: (5+0.9(10)=14)
* down: (5+0.9(1)=5.9)

Best action: **right**


**State (s_2)**

* up/right: (10+0.9(10)=19)
* left: (10+0.9(5)=14.5)
* down: (10+0.9(2)=11.8)

Best action: **up or right**


**State (s_3)**

* down/left: (1+0.9(1)=1.9)
* up: (1+0.9(5)=5.5)
* right: (1+0.9(2)=2.8)

Best action: **up**


**State (s_4)**

* down/right: (2+0.9(2)=3.8)
* up: (2+0.9(10)=11)
* left: (2+0.9(1)=2.9)

Best action: **up**


**_Improved Policy after Iteration 1_**

[
\pi_1:
\begin{cases}
s_1 \rightarrow \text{right} \
s_2 \rightarrow \text{up/right} \
s_3 \rightarrow \text{up} \
s_4 \rightarrow \text{up}
\end{cases}
]



`• Iteration 2:` Show the value function (V) after the second iteration


We now compute a second value update using value iteration.

 1. Policy Evaluation Step

Using value iteration update rule:

[
V_2(s)=\max_a \big(R(s)+\gamma V_1(s')\big)
]

We use the values from (V_1).


  **(s_1)**

Maximum from previous calculations = **14**

[
V_2(s_1)=14
]


**(s_2)**

Maximum from previous calculations = **19**

[
V_2(s_2)=19
]



**(s_3)**

Maximum from previous calculations = **5.5**

[
V_2(s_3)=5.5
]



**(s_4)**

Maximum from previous calculations = **11**

[
V_2(s_4)=11
]



  2. Value Function after Iteration 2

[
V_2=
\begin{cases}
s_1=14 \
s_2=19 \
s_3=5.5 \
s_4=11
\end{cases}
]



  3. Policy Improvement Step (Iteration 2)

The maximizing actions remain:

[
\pi_2=
\begin{cases}
s_1 \rightarrow \text{right} \
s_2 \rightarrow \text{up/right} \
s_3 \rightarrow \text{up} \
s_4 \rightarrow \text{up}
\end{cases}
]

No policy change from Iteration 1, so the policy is stabilizing.


**After Iteration 1:**

[
V_1 = {5,10,1,2}
]

**After Iteration 2:**

[
V_2 = {14,19,5.5,11}
]

**_Improved Policy:_**

* (s_1): right
* (s_2): up or right
* (s_3): up
* (s_4): up



`Reflection`

This Iteration 1 process shows how value iteration begins by evaluating the environment using a simple starting policy and then immediately improves it using the information gained. Because all initial state values are set to zero ((V_0=0)), the policy evaluation step under (\pi_0(\text{up}|s)=1) makes the updated values (V_1(s)) equal to the immediate rewards in each state (since the discounted future term (\gamma V_0(s')) contributes nothing yet). After obtaining these first value estimates, the policy improvement step looks one move ahead and selects the action in each state that leads to the highest discounted value of the next state, which naturally pushes the agent toward higher-reward states like (s_2). As a result, the improved policy (\pi_1) shifts away from always going “up” and instead recommends moving right from (s_1), staying up/right in (s_2), and moving up from (s_3) and (s_4), demonstrating the core idea that value iteration uses value estimates to gradually refine the policy toward better long-term outcomes.


### PROBLEM 3

`Task1: Update MDP Code`

1. Update the reward function to be a list of reward based on whether the state is terminal, grey,
or a regular state.

2. Run the existing code developed in class and obtain the optimal state-values and optimal policy.
Provide a figures of the gridworld with the obtained V∗ and π∗ (You can manually create a table)

In [33]:
from __future__ import annotations

import time
from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np

In [ ]:
State = Tuple[int, int]


@dataclass(frozen=True)
class Gridworld5x5:
    n_rows: int = 5
    n_cols: int = 5
    goal: State = (4, 4)
    grey_states: Tuple[State, ...] = ((1, 2), (3, 0), (0, 4))

    # (name, (dr, dc))
    actions: Tuple[Tuple[str, Tuple[int, int]], ...] = (
        ("R", (0, 1)),
        ("D", (1, 0)),
        ("L", (0, -1)),
        ("U", (-1, 0)),
    )

    def all_states(self) -> List[State]:
        return [(r, c) for r in range(self.n_rows) for c in range(self.n_cols)]

    def is_terminal(self, s: State) -> bool:
        return s == self.goal

    def reward(self, s: State) -> float:
        """Reward depends on the current state s ."""
        if s == self.goal:
            return 10.0
        if s in self.grey_states:
            return -5.0
        return -1.0

    def step(self, s: State, action_name: str) -> State:
        """Deterministic transition with wall-bounce (stay in place)."""
        if self.is_terminal(s):
            return s  # terminal state is absorbing for planning

        # find action delta
        delta = None
        for name, d in self.actions:
            if name == action_name:
                delta = d
                break
        if delta is None:
            raise ValueError(f"Unknown action: {action_name}")

        r, c = s
        dr, dc = delta
        nr, nc = r + dr, c + dc

        # wall -> stay
        if nr < 0 or nr >= self.n_rows or nc < 0 or nc >= self.n_cols:
            return s
        return (nr, nc)



In [ ]:
def value_iteration(
    env: Gridworld5x5,
    gamma: float = 0.9,
    theta: float = 1e-6,
    max_iters: int = 10000,
) -> Tuple[np.ndarray, np.ndarray, int, float]:
   
    start = time.perf_counter()

    V = np.zeros((env.n_rows, env.n_cols), dtype=float)
    V_new = np.zeros_like(V)

    # Map action index to name for policy storage/printing
    action_names = [name for name, _ in env.actions]

    it = 0
    for it in range(1, max_iters + 1):
        delta = 0.0

        for r in range(env.n_rows):
            for c in range(env.n_cols):
                s = (r, c)

                # Terminal: value can be set to its reward (or 0); assignment reward is +10 at goal.
                # We'll set V(goal) = 10 to reflect R(s_goal)=+10 clearly in the table.
                if env.is_terminal(s):
                    V_new[r, c] = env.reward(s)
                    continue

                # Bellman optimality backup
                best = -float("inf")
                for a in action_names:
                    s_next = env.step(s, a)
                    rr = env.reward(s)  # reward depends on current state
                    candidate = rr + gamma * V[s_next[0], s_next[1]]
                    if candidate > best:
                        best = candidate

                V_new[r, c] = best
                delta = max(delta, abs(V_new[r, c] - V[r, c]))

        V[:, :] = V_new  # copy new -> old for next iteration

        if delta < theta:
            break

    # Derive greedy policy π* from V*
    policy_idx = np.full((env.n_rows, env.n_cols), fill_value=-1, dtype=int)

    for r in range(env.n_rows):
        for c in range(env.n_cols):
            s = (r, c)
            if env.is_terminal(s):
                policy_idx[r, c] = -1
                continue

            best_a = 0
            best_val = -float("inf")
            for i, a in enumerate(action_names):
                s_next = env.step(s, a)
                rr = env.reward(s)
                val = rr + gamma * V[s_next[0], s_next[1]]
                if val > best_val:
                    best_val = val
                    best_a = i

            policy_idx[r, c] = best_a

    elapsed = time.perf_counter() - start
    return V, policy_idx, it, elapsed



In [36]:
def format_policy(env: Gridworld5x5, policy_idx: np.ndarray) -> List[List[str]]:
    """Turn action indices into arrows + mark special states."""
    idx_to_arrow = {0: "→", 1: "↓", 2: "←", 3: "↑", -1: "G"}  # -1 only used for goal
    grid = []
    for r in range(env.n_rows):
        row = []
        for c in range(env.n_cols):
            s = (r, c)
            if env.is_terminal(s):
                row.append("G")
            elif s in env.grey_states:
                # still show policy arrow but visually tag it as grey
                row.append(f"X{idx_to_arrow[policy_idx[r, c]]}")
            else:
                row.append(idx_to_arrow[policy_idx[r, c]])
        grid.append(row)
    return grid


In [37]:
def print_results(env, V, policy_idx, iters, elapsed, label="Value Iteration Results"):
    np.set_printoptions(precision=2, suppress=True)

    print(f"\n=== {label} ===")
    print(f"Iterations: {iters}")
    print(f"Optimization time: {elapsed:.6f} seconds")
    print("\nV* (state-value function):")
    print(V)

    print("\nπ* (greedy policy from V*):")
    policy_grid = format_policy(env, policy_idx)
    for r in range(env.n_rows):
        print(" ".join(f"{cell:>2}" for cell in policy_grid[r]))

    print("\nLegend:")
    print("  → Right, ↓ Down, ← Left, ↑ Up, G Goal/Terminal, X? = Grey state with suggested move")


if __name__ == "__main__":
    env = Gridworld5x5()

    V_star, pi_star_idx, n_iters, opt_time = value_iteration(
        env,
        gamma=0.9,
        theta=1e-6,
        max_iters=10000,
    )

    print_results(env, V_star, pi_star_idx, n_iters, opt_time)



=== Value Iteration Results ===
Iterations: 10
Optimization time: 0.001811 seconds

V* (state-value function):
[[-1.39 -0.43  0.63  1.81 -0.88]
 [-0.43  0.63 -2.19  3.12  4.58]
 [ 0.63  1.81  3.12  4.58  6.2 ]
 [-2.19  3.12  4.58  6.2   8.  ]
 [ 3.12  4.58  6.2   8.   10.  ]]

π* (greedy policy from V*):
 →  →  →  ↓ X↓
 →  ↓ X→  →  ↓
 →  →  →  →  ↓
X→  →  →  →  ↓
 →  →  →  →  G

Legend:
  → Right, ↓ Down, ← Left, ↑ Up, G Goal/Terminal, X? = Grey state with suggested move


`Task 2: Value Iteration Variations`

Implement the following variation of value iteration. Confirm that it reaches the same optimal statevalue function and policy.

1. In-Place Value Iteration: Use a single array to store the state values. This means that you
update the value of a state and immediately use that updated value in the subsequent updates.

In [38]:
# Reuse Gridworld5x5, format_policy, print_results from Task 1 code


def value_iteration_in_place(
    env,
    gamma: float = 0.9,
    theta: float = 1e-6,
    max_iters: int = 10000,
) -> Tuple[np.ndarray, np.ndarray, int, float]:
    """
    In-Place Value Iteration (Gauss–Seidel style):
        V(s) <- max_a [ R(s) + gamma * V(s') ]
    Updates are written back into V immediately within the same sweep.

    Returns:
      V* grid,
      greedy policy indices,
      iterations used,
      optimization time (seconds).
    """
    start = time.perf_counter()

    V = np.zeros((env.n_rows, env.n_cols), dtype=float)
    action_names = [name for name, _ in env.actions]

    it = 0
    for it in range(1, max_iters + 1):
        delta = 0.0

        # sweep through states (row-major order)
        for r in range(env.n_rows):
            for c in range(env.n_cols):
                s = (r, c)

                # Terminal: keep at terminal reward (clear for your V* table)
                if env.is_terminal(s):
                    old = V[r, c]
                    V[r, c] = env.reward(s)
                    delta = max(delta, abs(V[r, c] - old))
                    continue

                old = V[r, c]

                best = -float("inf")
                for a in action_names:
                    s_next = env.step(s, a)
                    rr = env.reward(s)  # reward depends on current state
                    candidate = rr + gamma * V[s_next[0], s_next[1]]  # uses UPDATED V when available
                    if candidate > best:
                        best = candidate

                V[r, c] = best
                delta = max(delta, abs(V[r, c] - old))

        if delta < theta:
            break

    # Derive greedy policy π* from V*
    policy_idx = np.full((env.n_rows, env.n_cols), fill_value=-1, dtype=int)

    for r in range(env.n_rows):
        for c in range(env.n_cols):
            s = (r, c)
            if env.is_terminal(s):
                policy_idx[r, c] = -1
                continue

            best_a = 0
            best_val = -float("inf")
            for i, a in enumerate(action_names):
                s_next = env.step(s, a)
                rr = env.reward(s)
                val = rr + gamma * V[s_next[0], s_next[1]]
                if val > best_val:
                    best_val = val
                    best_a = i

            policy_idx[r, c] = best_a

    elapsed = time.perf_counter() - start
    return V, policy_idx, it, elapsed


In [39]:
def compare_task1_vs_task2(env, gamma=0.9, theta=1e-6, max_iters=10000):
    V1, pi1, it1, t1 = value_iteration(env, gamma=gamma, theta=theta, max_iters=max_iters)
    V2, pi2, it2, t2 = value_iteration_in_place(env, gamma=gamma, theta=theta, max_iters=max_iters)

    # Check they converge to the same V* (within tolerance)
    same_values = np.allclose(V1, V2, atol=1e-4)
    same_policy = np.array_equal(pi1, pi2)

    print("\n=== Task 1 vs Task 2 Comparison ===")
    print(f"Task 1 (two-array):   iterations={it1}, time={t1:.6f}s")
    print(f"Task 2 (in-place):    iterations={it2}, time={t2:.6f}s")
    print(f"Same V* (tol 1e-4)?   {same_values}")
    print(f"Same π* exactly?      {same_policy}")

    return (V1, pi1, it1, t1), (V2, pi2, it2, t2)


if __name__ == "__main__":
    env = Gridworld5x5()
    (V_star_1, pi_1, it1, t1), (V_star_2, pi_2, it2, t2) = compare_task1_vs_task2(env)

    # print("\n--- Task 2 Results (In-Place) ---")
    # print_results(env, V_star_2, pi_2, it2, t2)
    print_results(env, V_star_1, pi_1, it1, t1, label="Task 1 — Standard Value Iteration (Two-Array)")
    print_results(env, V_star_2, pi_2, it2, t2, label="Task 2 — In-Place Value Iteration")




=== Task 1 vs Task 2 Comparison ===
Task 1 (two-array):   iterations=10, time=0.001406s
Task 2 (in-place):    iterations=10, time=0.001909s
Same V* (tol 1e-4)?   True
Same π* exactly?      True

=== Task 1 — Standard Value Iteration (Two-Array) ===
Iterations: 10
Optimization time: 0.001406 seconds

V* (state-value function):
[[-1.39 -0.43  0.63  1.81 -0.88]
 [-0.43  0.63 -2.19  3.12  4.58]
 [ 0.63  1.81  3.12  4.58  6.2 ]
 [-2.19  3.12  4.58  6.2   8.  ]
 [ 3.12  4.58  6.2   8.   10.  ]]

π* (greedy policy from V*):
 →  →  →  ↓ X↓
 →  ↓ X→  →  ↓
 →  →  →  →  ↓
X→  →  →  →  ↓
 →  →  →  →  G

Legend:
  → Right, ↓ Down, ← Left, ↑ Up, G Goal/Terminal, X? = Grey state with suggested move

=== Task 2 — In-Place Value Iteration ===
Iterations: 10
Optimization time: 0.001909 seconds

V* (state-value function):
[[-1.39 -0.43  0.63  1.81 -0.88]
 [-0.43  0.63 -2.19  3.12  4.58]
 [ 0.63  1.81  3.12  4.58  6.2 ]
 [-2.19  3.12  4.58  6.2   8.  ]
 [ 3.12  4.58  6.2   8.   10.  ]]

π* (greedy policy

`Reflection`

| Metric                             | Task 1 (Two-Array) | Task 2 (In-Place) |
| ---------------------------------- | --------------------- | -------------------- |
| Iterations (Sweeps)                | 10                    | 10                   |
| Optimization Time (seconds)        | 0.009354 s            | 0.008264 s           |
| Same Optimal Value Function (V^*)? | —                     | Yes                  |
| Same Optimal Policy ( \pi^* )?     | —                     | Yes                  |


In Task 1 and Task 2, we implemented two versions of Value Iteration to solve the 5×5 Gridworld. Both approaches successfully converged to the same optimal state-value function 𝑉 and the same optimal policy 𝜋. The values increased as states got closer to the goal at (4,4), and states near the grey penalty cells had lower values. This confirms that the algorithm correctly learned to prefer paths that maximize long-term reward while avoiding unfavorable states.

When comparing performance, both methods converged in 10 iterations. However, the in-place Value Iteration ran slightly faster (0.008264 seconds) than the two-array version (0.009354 seconds). This small difference occurs because the in-place method updates values immediately and can use newly improved values within the same sweep. Even though both methods have the same theoretical complexity, the in-place version can be more efficient in practice.

### PROBLEM 4

`Task`

Implement the off-policy Monte Carlo with Importance sampling algorithm to estimate the value
function for the given gridworld. Use a fixed behavior policy b(a|s) (e.g., a random policy) to generate
episodes and a greedy target policy

In [ ]:
State = Tuple[int, int]

# Environment is the same as Problem 3

class Gridworld5x5:
    def __init__(self):
        self.n_rows = 5
        self.n_cols = 5
        self.goal: State = (4, 4)
        self.grey_states = {(1, 2), (3, 0), (0, 4)}

        # action index -> (name, (dr, dc))
        self.actions = [
            ("R", (0, 1)),
            ("D", (1, 0)),
            ("L", (0, -1)),
            ("U", (-1, 0)),
        ]

    def is_terminal(self, s: State) -> bool:
        return s == self.goal

    def reward(self, s: State) -> float:
        # reward depends on current state (as per assignment)
        if s == self.goal:
            return 10.0
        if s in self.grey_states:
            return -5.0
        return -1.0

    def step(self, s: State, a_idx: int) -> State:
        # terminal is absorbing
        if self.is_terminal(s):
            return s

        dr, dc = self.actions[a_idx][1]
        r, c = s
        nr, nc = r + dr, c + dc

        # wall -> stay
        if nr < 0 or nr >= self.n_rows or nc < 0 or nc >= self.n_cols:
            return s
        return (nr, nc)

    def all_states(self) -> List[State]:
        return [(r, c) for r in range(self.n_rows) for c in range(self.n_cols)]



In [41]:
def policy_to_arrows(env: Gridworld5x5, pi: np.ndarray) -> List[List[str]]:
    # pi stores action index per state; -1 for terminal
    arrows = {0: "→", 1: "↓", 2: "←", 3: "↑", -1: "G"}
    grid = []
    for r in range(env.n_rows):
        row = []
        for c in range(env.n_cols):
            s = (r, c)
            if env.is_terminal(s):
                row.append("G")
            elif s in env.grey_states:
                row.append("X" + arrows[int(pi[r, c])])
            else:
                row.append(arrows[int(pi[r, c])])
        grid.append(row)
    return grid


In [42]:
def print_value_and_policy(env: Gridworld5x5, V: np.ndarray, pi: np.ndarray, title: str):
    np.set_printoptions(precision=2, suppress=True)
    print(f"\n=== {title} ===")
    print("\nEstimated V (5x5):")
    print(V)

    print("\nGreedy policy π (arrows):")
    grid = policy_to_arrows(env, pi)
    for r in range(env.n_rows):
        print(" ".join(f"{cell:>2}" for cell in grid[r]))

    print("\nLegend: → Right, ↓ Down, ← Left, ↑ Up, G Goal, X? Grey state")



In [44]:
# Behavior policy b(a|s): fixed uniform random

def behavior_policy_probs(n_actions: int) -> np.ndarray:
    return np.ones(n_actions) / n_actions



In [45]:
# Generate an episode under behavior policy b

def generate_episode(
    env: Gridworld5x5,
    start_state: State,
    gamma: float,
    rng: np.random.Generator,
    max_steps: int = 200,
) -> List[Tuple[State, int, float]]:
    """
    Episode = list of (state, action, reward).
    Reward here is R(s_t) based on current state, matching assignment.
    """
    episode = []
    s = start_state

    b_probs = behavior_policy_probs(len(env.actions))

    for _ in range(max_steps):
        # choose action from behavior policy
        a = rng.choice(len(env.actions), p=b_probs)
        r = env.reward(s)
        episode.append((s, a, r))

        s = env.step(s, a)
        if env.is_terminal(s):
            # include terminal state's reward once (optional but consistent):
            # In your Problem 3 you set V(goal)=10. Here we can add final transition reward.
            # We'll append terminal reward as a final step with dummy action = -1.
            episode.append((s, -1, env.reward(s)))
            break

    return episode



In [46]:

# Off-policy Monte Carlo Control (Weighted Importance Sampling)

def off_policy_mc_control_weighted_is(
    env: Gridworld5x5,
    num_episodes: int = 20000,
    gamma: float = 0.9,
    max_steps: int = 200,
    seed: int = 7,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, float]:
    """
    Learns Q(s,a) and a greedy target policy π from episodes generated by behavior policy b.
    Uses Weighted Importance Sampling to update Q.

    Returns:
      V_est (5x5),
      pi_greedy (5x5 action indices; -1 at terminal),
      Q (5x5x|A|),
      elapsed time.
    """
    start = time.perf_counter()
    rng = np.random.default_rng(seed)

    nA = len(env.actions)

    # Q and C (cumulative weights) arrays
    Q = np.zeros((env.n_rows, env.n_cols, nA), dtype=float)
    C = np.zeros_like(Q)

    # target policy π initialized arbitrarily (e.g., all "Right")
    pi = np.zeros((env.n_rows, env.n_cols), dtype=int)
    pi[env.goal[0], env.goal[1]] = -1  # terminal marker

    b_probs = behavior_policy_probs(nA)

    # sample starting states uniformly (excluding terminal)
    non_terminal_states = [s for s in env.all_states() if not env.is_terminal(s)]

    for _ in range(num_episodes):
        s0 = non_terminal_states[rng.integers(len(non_terminal_states))]
        episode = generate_episode(env, s0, gamma, rng, max_steps=max_steps)

        G = 0.0
        W = 1.0

        # Work backward through episode (skip last terminal dummy action step)
        for (s, a, r) in reversed(episode):
            if a == -1:
                # terminal dummy step: just accumulate reward and continue
                G = gamma * G + r
                continue

            r0, c0 = s
            G = gamma * G + r  # return from this time step

            # Weighted IS update
            C[r0, c0, a] += W
            Q[r0, c0, a] += (W / C[r0, c0, a]) * (G - Q[r0, c0, a])

            # improve target policy greedily w.r.t Q
            pi[r0, c0] = int(np.argmax(Q[r0, c0, :]))

            # If behavior took an action that target would NOT take, importance weight becomes 0 thereafter
            if a != pi[r0, c0]:
                break

            # update importance weight: W *= π(a|s)/b(a|s)
            # π is deterministic greedy => π(a|s)=1 for chosen greedy action
            W *= 1.0 / b_probs[a]

    elapsed = time.perf_counter() - start

    # compute V from Q under greedy π
    V = np.zeros((env.n_rows, env.n_cols), dtype=float)
    for r in range(env.n_rows):
        for c in range(env.n_cols):
            s = (r, c)
            if env.is_terminal(s):
                V[r, c] = env.reward(s)
            else:
                V[r, c] = np.max(Q[r, c, :])

    return V, pi, Q, elapsed



In [49]:
#  compare MC V to Value Iteration V*
def mse(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.mean((a - b) ** 2))

In [50]:
if __name__ == "__main__":
    env = Gridworld5x5()

    # Run off-policy MC control
    V_mc, pi_mc, Q_mc, t_mc = off_policy_mc_control_weighted_is(
        env,
        num_episodes=20000,   # increase for tighter match to VI
        gamma=0.9,
        max_steps=200,
        seed=7,
    )

    print_value_and_policy(env, V_mc, pi_mc, title="Problem 4 — Off-policy MC (Weighted IS)")

    print(f"\nEpisodes: 20000")
    print(f"Optimization time: {t_mc:.6f} seconds")





=== Problem 4 — Off-policy MC (Weighted IS) ===

Estimated V (5x5):
[[-1.39 -0.44  0.62  1.8  -0.9 ]
 [-0.44  0.62 -2.2   3.11  4.57]
 [ 0.62  1.8   3.1   4.56  6.19]
 [-2.2   3.11  4.56  6.19  8.  ]
 [ 3.1   4.56  6.19  8.   10.  ]]

Greedy policy π (arrows):
 ↓  ↓  →  ↓ X↓
 →  ↓ X↓  →  ↓
 →  ↓  →  ↓  ↓
X→  →  ↓  ↓  ↓
 →  →  →  →  G

Legend: → Right, ↓ Down, ← Left, ↑ Up, G Goal, X? Grey state

Episodes: 20000
Optimization time: 42.332518 seconds


In [ ]:
# the v from problem 3 (value iteration) is V_star_2
V_vi = V_star_2
print("MSE vs Value Iteration:", mse(V_mc, V_vi))

MSE vs Value Iteration: 0.0001759747569171575
